var airports = [
	"Sault Sainte Marie - Sault Ste Marie (YAM)",
	"Winnipeg - Winnipeg St Andrews (YAV)",
	"Halifax - Shearwater (YAW)",
	"St. Anthony - St Anthony (YAY)",
	"Tofino - Tofino (YAZ)",
	"Pelly Bay - Kugaaruk (YBB)",
	"Baie Comeau - Baie Comeau (YBC)",
	"Bagotville - Bagotville (YBG)",
	"Baker Lake - Baker Lake (YBK)",
	"Campbell River - Campbell River (YBL)",
	"Brandon - Brandon Muni (YBR)",
	"Cambridge Bay - Cambridge Bay (YCB)",
	"Nanaimo - Nanaimo (YCD)",
	"Castlegar - Castlegar (YCG)",
	"Chatham - Miramichi (YCH)",
	"Charlo - Charlo (YCL)",
	"Coppermine - Kugluktuk (YCO)",
	"Coronation - Coronation (YCT)",
	"Chilliwack - Chilliwack (YCW)",
	"Clyde River - Clyde River (YCY)",
	"Coral Harbour - Fairmont Hot Springs (YZS)",
	"Dawson - Dawson City (YDA)",
	"Burwash - Burwash (YDB)",
	"Princeton - Princeton (YDC)",
	"Deer Lake - Deer Lake (YDF)",
	"Dease Lake - Dease Lake (YDL)",
	"Dauphin - Dauphin Barker (YDN)",
	"Dawson Creek - Dawson Creek (YDQ)",
	"Edmonton - Edmonton Intl (YEG)",
	"Eskimo Point - Arviat (YEK)",
	"Estevan - Estevan (YEN)",
	"Edson - Edson (YET)",
	"Eureka - Eureka (YEU)",
	"Inuvik - Inuvik Mike Zubko (YEV)",
	"Iqaluit - Iqaluit (YFB)",
	"Fredericton - Fredericton (YFC)",
	"Forestville - Forestville ()",
	"Flin Flon - Flin Flon (YFO)",
	"Fort Resolution - Fort Resolution (YFR)",
	"Fort Simpson - Fort Simpson (YFS)",
	"Kingston - Kingston (YGK)",
	"La Grande Riviere - La Grande Riviere (YGL)",
	"Gaspe - Gaspe (YGP)",
	"Geraldton - Geraldton Greenstone Regional (YGQ)",
	"Iles De La Madeleine - Iles De La Madeleine (YGR)",
	"Hudson Bay - Hudson Bay (YHB)",
	"Dryden - Dryden Rgnl (YHD)",
	"Holman Island - Ulukhaktok Holman (YHI)",
	"Gjoa Haven - Gjoa Haven (YHK)",
	"Hamilton - Hamilton (YHM)",
	"Montreal - St Hubert (YHU)",
	"Hay River - Hay River (YHY)",
	"Halifax - Halifax Intl (YHZ)",
	"Atikokan - Atikokan Muni (YIB)",
	"Pond Inlet - Pond Inlet (YIO)",
	"St. Jean - St Jean (YJN)",
	"Stephenville - Stephenville (YJT)",
	"Kamloops - Kamloops (YKA)",
	"Waterloo - Waterloo (YKF)",
	"Schefferville - Schefferville (YKL)",
	"Kindersley - Kindersley (YKY)",
	"Toronto - Buttonville Muni (YKZ)",
	"Chapleau - Chapleau (YLD)",
	"Meadow Lake - Meadow Lake (YLJ)",
	"Lloydminster - Lloydminster (YLL)",
	"Alert - Alert (YLT)",
	"Kelowna - Kelowna (YLW)",
	"Mayo - Mayo (YMA)",
	"Moose Jaw - Moose Jaw Air Vice Marshal C M Mcewen (YMJ)",
	"Fort Mcmurray - Fort Mcmurray (YMM)",
	"Moosonee - Moosonee (YMO)",
	"Maniwaki - Maniwaki (YMW)",
	"Montreal - Montreal Intl Mirabel (YMX)",
	"Natashquan - Natashquan (YNA)",
	"Gatineau - Gatineau (YND)",
	"Matagami - Matagami (YNM)",
	"Old Crow - Old Crow (YOC)",
	"Cold Lake - Cold Lake (YOD)",
	"High Level - High Level (YOJ)",
	"Ottawa - Ottawa Macdonald Cartier Intl (YOW)",
	"Prince Albert - Prince Albert Glass Field (YPA)",
	"Peace River - Peace River (YPE)",
	"Portage-la-prairie - Southport (YPG)",
	"Pitt Meadows - Pitt Meadows ()",
	"Pickle Lake - Pickle Lake (YPL)",
	"Port Menier - Port Menier (YPN)",
	"Peterborough - Peterborough (YPQ)",
	"Prince Pupert - Prince Rupert (YPR)",
	"Fort Chipewyan - Fort Chipewyan (YPY)",
	"Muskoka - Muskoka (YQA)",
	"Quebec - Quebec Jean Lesage Intl (YQB)",
	"Red Deer Industrial - Red Deer Regional (YQF)",
	"Windsor - Windsor (YQG)",
	"Watson Lake - Watson Lake (YQH)",
	"Kenora - Kenora (YQK)",
	"Lethbridge - Lethbridge (YQL)",
	"Moncton - Greater Moncton Intl (YQM)",
	"Comox - Comox (YQQ)",
	"Regina - Regina Intl (YQR)",
	"Thunder Bay - Thunder Bay (YQT)",
	"Grande Prairie - Grande Prairie (YQU)",
	"Yorkton - Yorkton Muni (YQV)",
	"North Battleford - North Battleford (YQW)",
	"Gander - Gander Intl (YQX)",
	"Sydney - Sydney (YQY)",
	"Quesnel - Quesnel (YQZ)",
	"Resolute - Resolute Bay (YRB)",
	"Riviere Du Loup - Riviere Du Loup (YRI)",
	"Roberval - Roberval (YRJ)",
	"Rocky Mountain House - Rocky Mountain House (YRM)",
	"Rankin Inlet - Rankin Inlet (YRT)",
	"Sudbury - Sudbury (YSB)",
	"Sherbrooke - Sherbrooke (YSC)",
	"St. John - Saint John (YSJ)",
	"Fort Smith - Fort Smith (YSM)",
	"Nanisivik - Nanisivik (YSR)",
	"Summerside - Summerside (YSU)",
	"Sachs Harbour - Sachs Harbour (YSY)",
	"Cape Dorset - Cape Dorset (YTE)",
	"Thompson - Thompson (YTH)",
	"Trenton - Trenton (YTR)",
	"Timmins - Timmins (YTS)",
	"Toronto - City Centre (YTZ)",
	"Tuktoyaktuk - Tuktoyaktuk (YUB)",
	"Montreal - Pierre Elliott Trudeau Intl (YUL)",
	"Repulse Bay - Repulse Bay (YUT)",
	"Hall Beach - Hall Beach (YUX)",
	"Rouyn - Rouyn Noranda (YUY)",
	"La Ronge - La Ronge (YVC)",
	"Vermillion - Vermilion (YVG)",
	"Broughton Island - Qikiqtarjuaq (YVM)",
	"Val D'or - Val D Or (YVO)",
	"Quujjuaq - Kuujjuaq (YVP)",
	"Norman Wells - Norman Wells (YVQ)",
	"Vancouver - Vancouver Intl (YVR)",
	"Buffalo Narrows - Buffalo Narrows (YVT)",
	"Wiarton - Wiarton (YVV)",
	"Petawawa - Petawawa (YWA)",
	"Winnipeg - Winnipeg Intl (YWG)",
	"Wabush - Wabush (YWK)",
	"Williams Lake - Williams Lake (YWL)",
	"Wrigley - Wrigley (YWY)",
	"Cranbrook - Canadian Rockies Intl (YXC)",
	"Edmonton - Edmonton City Centre (YXD)",
	"Saskatoon - Saskatoon J G Diefenbaker Intl (YXE)",
	"Medicine Hat - Medicine Hat (YXH)",
	"Fort Saint John - Fort St John (YXJ)",
	"Sioux Lookout - Sioux Lookout (YXL)",
	"Pangnirtung - Pangnirtung (YXP)",
	"Earlton - Timiskaming Rgnl (YXR)",
	"Prince George - Prince George (YXS)",
	"Terrace - Terrace (YXT)",
	"London - London (YXU)",
	"Abbotsford - Abbotsford (YXX)",
	"Whitehorse - Whitehorse Intl (YXY)",
	"North Bay - North Bay (YYB)",
	"Calgary - Calgary Intl (YYC)",
	"Smithers - Smithers (YYD)",
	"Fort Nelson - Fort Nelson (YYE)",
	"Penticton - Penticton (YYF)",
	"Charlottetown - Charlottetown (YYG)",
	"Spence Bay - Taloyoak (YYH)",
	"Victoria - Victoria Intl (YYJ)",
	"Lynn Lake - Lynn Lake (YYL)",
	"Swift Current - Swift Current (YYN)",
	"Churchill - Churchill (YYQ)",
	"Goose Bay - Goose Bay (YYR)",
	"St. John's - St Johns Intl (YYT)",
	"Kapuskasing - Kapuskasing (YYU)",
	"Armstrong - Armstrong (YYW)",
	"Mont Joli - Mont Joli (YYY)",
	"Toronto - Lester B Pearson Intl (YYZ)",
	"Toronto - Downsview (YZD)",
	"Gore Bay - Gore Bay Manitoulin (YZE)",
	"Yellowknife - Yellowknife (YZF)",
	"Slave Lake - Slave Lake (YZH)",
	"Sandspit - Sandspit (YZP)",
	"Sarnia - Chris Hadfield (YZR)",
	"Port Hardy - Port Hardy (YZT)",
	"Whitecourt - Whitecourt (YZU)",
	"Sept-iles - Sept Iles (YZV)",
	"Teslin - Teslin (YZW)",
	"Greenwood - Greenwood (YZX)",
	"Faro - Faro (ZFA)",
	"Fort Mcpherson - Fort Mcpherson (ZFM)",
	"Panorama - RK Heliplex ()",
	"Ekati - Ekati (YOA)",
	"Victoria - Victoria Inner Harbour Airport (YWH)",
	"Vancouver - Vancouver Coal Harbour (CXH)",
	"Aklavik - Aklavik (LAK)",
	"Deline - Deline (YWJ)",
	"Tulita - Tulita (ZFN)",
	"Fort Good Hope - Fort Good Hope (YGH)",
	"Inuvik - Inuvik Town ()",
	"Inuvik - INAWR ()",
	"Paulatuk - Paulatuk (YPC)",
	"Nicholson Peninsula - Nicholson Peninsula ()",
	"Wollaston Lake - Wollaston Lake Airport (ZWL)",
	"Churchill Falls - Churchill Falls Airport (ZUM)",
	"Shamattawa - Shamattawa Airport (ZTM)",
	"Sandy Lake - Sandy Lake Airport (ZSJ)",
	"Round Lake - Round Lake (Weagamow Lake) Airport (ZRJ)",
	"Sachigo Lake - Sachigo Lake Airport (ZPB)",
	"Masset - Masset Airport (ZMT)",
	"Muskrat Dam - Muskrat Dam Airport (MSA)",
	"Kashechewan - Kashechewan Airport (ZKE)",
	"Swan River - Swan River Airport (ZJN)",
	"Gods River - Gods River Airport (ZGI)",
	"Fond-Du-Lac - Fond-Du-Lac Airport (ZFD)",
	"Eastmain River - Eastmain River Airport (ZEM)",
	"Bathurst - Bathurst Airport (ZBF)",
	"Ilford - Ilford Airport (ILF)",
	"York Landing - York Landing Airport (ZAC)",
	"Salluit - Salluit Airport (YZG)",
	"Whale Cove - Whale Cove Airport (YXN)",
	"Webequie - Webequie Airport (YWP)",
	"Deer Lake - Deer Lake Airport (YVZ)",
	"Big Trout Lake - Big Trout Lake Airport (YTL)",
	"St. Theresa Point - St. Theresa Point Airport (YST)",
	"Sanikiluaq - Sanikiluaq Airport (YSK)",
	"Stony Rapids - Stony Rapids Airport (YSF)",
	"Red Lake - Red Lake Airport (YRL)",
	"Gamètì - Rae Lakes Airport (YRA)",
	"Nakina - Nakina Airport (YQN)",
	"The Pas - The Pas Airport (YQD)",
	"Powell River - Powell River Airport (YPW)",
	"Peawanuck - Peawanuck Airport (YPO)",
	"Pikangikum - Pikangikum Airport (YPM)",
	"Inukjuak - Inukjuak Airport (YPH)",
	"Oxford House - Oxford House Airport (YOH)",
	"Points North Landing - Points North Landing Airport (YNL)",
	"Norway House - Norway House Airport (YNE)",
	"Wemindji - Wemindji Airport (YNC)",
	"Umiujaq - Umiujaq Airport (YUD)",
	"Chibougamau - Chapais Airport (YMT)",
	"Mary's Harbour - Mary's Harbour Airport (YMH)",
	"Kangiqsualujjuaq - Kangiqsualujjuaq (Georges River) Airport (XGR)",
	"Lutselk'e - Lutselk'e Airport (YSG)",
	"Lansdowne House - Lansdowne House Airport (YLH)",
	"Kimmirut - Kimmirut Airport (YLC)",
	"Aupaluk - Aupaluk Airport (YPJ)",
	"Waskaganish - Waskaganish Airport (YKQ)",
	"Akulivik - Akulivik Airport (AKV)",
	"Island Lake - Island Lake Airport (YIV)",
	"Ivujivik - Ivujivik Airport (YIK)",
	"Chevery - Chevery Airport (YHR)",
	"Hopedale - Hopedale Airport (YHO)",
	"Nemiscau - Nemiscau Airport (YNS)",
	"Vancouver - Vancouver Harbour Water Airport (YHC)",
	"Quaqtaq - Quaqtaq Airport (YQC)",
	"Grise Fiord - Grise Fiord Airport (YGZ)",
	"Gillam - Gillam Airport (YGX)",
	"Kuujjuarapik - Kuujjuarapik Airport (YGW)",
	"Igloolik - Igloolik Airport (YGT)",
	"Gods Lake Narrows - Gods Lake Narrows Airport (YGO)",
	"Texada - Texada Gillies Bay Airport (YGB)",
	"Makkovik - Makkovik Airport (YMN)",
	"Fort Hope - Fort Hope Airport (YFH)",
	"Fort Albany - Fort Albany Airport (YFA)",
	"Fort Severn - Fort Severn Airport (YER)",
	"Nain - Nain Airport (YDP)",
	"Chesterfield Inlet - Chesterfield Inlet Airport (YCS)",
	"Cartwright - Cartwright Airport (YRF)",
	"Lourdes-De-Blanc-Sablon - Lourdes De Blanc Sablon Airport (YBX)",
	"Uranium City - Uranium City Airport (YBE)",
	"Lac Du Bonnet - Lac Du Bonnet Airport ()",
	"Attawapiskat - Attawapiskat Airport (YAT)",
	"Kangirsuk - Kangirsuk Airport (YKG)",
	"Kasabonika - Kasabonika Airport (XKS)",
	"Fort Frances - Fort Frances Municipal Airport (YAG)",
	"Cat Lake - Cat Lake Airport (YAC)",
	"La Tabatière - La Tabatière Airport (ZLT)",
	"Tête-à-la-Baleine - Tête-à-la-Baleine Airport (ZTB)",
	"Chisasibi - Chisasibi Airport (YKU)",
	"Poplar Hill - Poplar Hill Airport (YHP)",
	"Ogoki Post - Ogoki Post Airport (YOG)",
	"Kingfisher Lake - Kingfisher Lake Airport (KIF)",
	"Bearskin Lake - Bearskin Lake Airport (XBE)",
	"North Spirit Lake - North Spirit Lake Airport (YNO)",
	"Wunnumin Lake - Wunnumin Lake Airport (WNN)",
	"Angling Lake - Wapekeka Airport (YAX)",
	"Summer Beaver - Summer Beaver Airport (SUR)",
	"Whatì - Whatì Airport (YLE)",
	"Colville Lake - Colville Lake Airport (YCK)",
	"Rigolet - Rigolet Airport (YRG)",
	"Port Hope Simpson - Port Hope Simpson Airport (YHA)",
	"St. Lewis - St. Lewis (Fox Harbour) Airport (YFX)",
	"Williams Harbour - Williams Harbour Airport (YWM)",
	"Anahim Lake - Anahim Lake Airport (YAA)",
	"Whistler - Whistler/Green Lake Water Aerodrome (YWS)",
	"St-Augustin - St Augustin Airport (YIF)",
	"Bonaventure - Bonaventure Airport (YVB)",
	"Bella Coola - Bella Coola Airport (QBC)",
	"Tasiujaq - Tasiujaq Airport (YTQ)",
	"Puvirnituq - Puvirnituq Airport (YPX)",
	"Prince Rupert - Seal Cove Seaplane Base (ZSW)",
	"Berens River - Berens River (YBV)",
	"Port Simpson - Seaplane Base (YPI)",
	"Mont-Tremblant - Riviere Rouge - Mont-Tremblant International Inc. Airport (YTM)",
	"Fox Harbour - Fox Harbour Airport ()",
	"Natuashish - Natuashish Airport ()",
	"Postville - Postville Airport (YSO)",
	"Kangiqsujuaq - Kangiqsujuaq - Wakeham Bay Airport (YWB)",
	"Alma - Alma Airport (YTF)",
	"Havre-Saint-Pierre - Havre Saint-Pierre Airport (YGV)",
	"Rimouski - Rimouski Airport (YXK)",
	"Tadoule Lake - Tadoule Lake Airport (XTL)",
	"Lac Brochet - Lac Brochet Airport (XLB)",
	"South Indian Lake - South Indian Lake Airport (XSI)",
	"Brochet - Brochet Airport (YBT)",
	"Little Grand Rapids - Little Grand Rapids Airport (ZGR)",
	"Cross Lake - Cross Lake - Charlie Sinclair Memorial Airport (YCR)",
	"Red Sucker Lake - Red Sucker Lake Airport (YRS)",
	"Rainbow Lake - Rainbow Lake Airport (YOP)",
	"Bonnyville - Bonnyville Airport (YBY)",
	"Nanaimo - Nanaimo Harbour Water Airport (ZNA)",
	"Ganges - Ganges Water Aerodrome ()",
	"Bedwell Harbour - Bedwell Harbour Water Aerdrome ()",
	"Qualicum Beach - Qualicum Beach Airport (XQU)",
	"Fort St. James - Fort St. James - Perison Airport (YJM)",
	"Boundary Bay - Boundary Bay Airport (YDT)",
	"Langley Township - Langley Regional Airport ()",
	"Bella Bella - Bella Bella Airport (ZEL)",
	"Sechelt-Gibsons - Sechelt Aerodrome (YHS)",
	"Wekweeti - Wekweeti Airport ()",
	"Victoria - Victoria Cruise Pier ()",
	"Montreal - Central Railway Station (YMY)",
	"Toronto - Union Station (YBZ)",
	"Yarmouth - Yarmouth Airport (YQI)",
	"Fraser BC - Fraser Railroad Station ()",
	"Carcross YT - Carcross ()",
	"Nanaimo Station British Columbia - Nanaimo Train Station ()",
	"Victoria Station British Columbia - Victoria Rail Station British Columbia ()",
	"Vancouver BC - Vancouver Cruise Terminal ()",
	"Niagara Falls - Niagara Falls Station ()",
	"Burlington - Burlington Airpark ()",
	"Waterville - Kings County Municipal Airport ()",
	"Brampton - Brampton Airport ()",
	"Toronto - Toronto Coach Terminal ()",
	"Montreal - Montreal Central Bus Station ()",
	"Oshawa - Oshawa Airport (YOO)",
	"Ottawa - Train Station (XDS)",
	"Belleville - Train Station (XVV)",
	"Edmonton - Train Station (XZL)",
	"Churchill - Train Station (XAD)",
	"Winnipeg - Train Station (XEF)",
	"Kingston - Kingston VIA Station ()",
	"Mackenzie British Columbia - Mackenzie Airport (YZY)",
	"Calgary - Calgary Springbank Airport (YBW)",
	"Golden - Golden Airport (YGE)",
	"Revelstoke - Revelstoke Airport (YRV)",
	"Vancouver - Pacific Station ()",
	"Kingston - Kingston Train Station (XEG)",
	"Dorval - Dorval Railway Station (XAX)",
	"Brockville - Brockville Megabus Stop ()",
	"Brockville - Brockville VIA Station ()",
	"Pembroke - Pembroke Airport (YTA)",
	"Suffield - Suffield Heliport (YSD)",
	"Wainwright - Field 21 ()",
	"Wainwright - Field 21 ()",
	"Big Bay - Big Bay Water Aerodrome (YRR)",
	"Cornwall - Cornwall Regional Airport (YCC)",
	"La Romaine - La Romaine Airport ()",
	"Kegaska - Kegaska Airport (ZKG)",
	"Black Tickle - Black Tickle Airport (YBI)",
	"Trail - Trail Airport (YZZ)",
	"Patricia Bay - Victoria Airport Water Aerodrome ()",
	"Arctic Bay - Arctic Bay Airport (YAB)",
	"Hope Bay - Hope Bay Aerodrome ()",
	"Keewaywin - Keewaywin (KEW)",
	"Marathon - Marathon (YSP)",
	"Hearst - Rene Fontaine (YHF)",
	"Hornepayne - Hornepayne (YHN)",
	"Kirkland Lake - Kirkland Lake (YKX)",
	"Manitouwadge - Manitouwadge (YMG)",
	"Wawa - Wawa (YXZ)",
	"Manitowaning - Manitoulin East (YEM)",
	"Slate Falls - Slate Falls ()",
	"Collingwood - Collingwood ()",
	"Brantford - Brantford (YFD)",
	"One Hundred Mile House - One Hundred Mile House Airport ()",
	"108 Mile Ranch - South Cariboo Regional Airport (ZML)",
	"Gimli - Gimli Industrial Park Airport (YGM)",
	"Matheson Island - Matheson Island Airport ()",
	"Matheson Island - Matheson Island Airport ()",
	"Matheson Island - Matheson Island Airport ()",
	"High River - High River Regional Airport ()",
	"Bob Quinn Lake - Bob Quinn Lake (YBO)",
	"Montreal - All Airports (YMQ)",
	"Toronto - All Airports (YTO)",
	"Trois Rivieres - Trois Rivieres Airport (YRQ)",
	"Bogande - Bogande Airport (XBG)",
	"Yarmouth NS - Yarmouth Ferry Terminal ()",
	"Guelph - CNC4 ()",
	"Geulph - CNC4 ()",
];